name: Security  # Defines the name of the workflow.

on:
  push:
    branches:
      - main  # Specifies that this workflow runs on pushes to the 'main' branch.

jobs:
  build:
    name: Build, Analyze & Scan  # Names the job within the workflow.
    runs-on: ubuntu-latest  # Specifies that the job runs on the latest version of the Ubuntu runner.

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Checks out the repository code to the GitHub runner.
        with:
          fetch-depth: 0  # Fetches the full history of the repository to ensure a complete analysis by SonarQube.
          
      - name: Set up Node.js
        uses: actions/setup-node@v4.0.3  # Sets up Node.js environment for the job.
        with:
          node-version: 18  # Specifies Node.js version 18 for compatibility.

      - name: Install Dependencies
        run: npm install  # Installs project dependencies using npm.

      - name: Start Application
        run: npm start &  # Starts the application in the background.
        # Note: Adjust the start command based on your application setup.

      - name: Wait for Application to Start
        run: sleep 20  # Waits for the application to fully start before proceeding.
        # Adjust the sleep duration based on your application's startup time.

      - name: Run SonarQube Analysis
        uses: sonarsource/sonarqube-scan-action@master  # Runs the SonarQube analysis action to scan the code for quality issues.
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Sets the SonarQube authentication token from GitHub secrets.
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}  # Sets the URL of the SonarQube server from GitHub secrets.

      - name: Run OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.10.0  # Runs the OWASP ZAP scan against the local application.
        with:
          target: 'http://localhost:4200'  # Specifies the URL of the local application to scan.
          allow_issue_writing: false  # Disables writing any new issues found by ZAP to the report.

      - name: Shutdown Application
        run: kill $(lsof -t -i:4200)  # Stops the local application after scanning.
        # Adjust the port if your application runs on a different port.
