name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build, Test, and Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Start Application
        run: npm start &

      - name: Wait for Application to Start
        run: sleep 20

      - name: Run OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          target: 'http://localhost:4200'

      - name: Shutdown Application
        run: kill $(lsof -t -i:3000)
